### ISSUE TITLE
Use an installer 

### ISSUE THREAD

**Issue by Draluy** [Draluy/chocoratage#10]
- provide a more user friendly experience
- install the program as a process, with root permissions, so it cannot be killed by a chocoblaster?

**Comment by Draluy** [comment]
Check http://izpack.org/

**Comment by fabmars** [comment]
Other options:
* Install4J https://www.ej-technologies.com/buy/install4j/select
* InstallBuilder: https://installbuilder.bitrock.com/purchase.html
Both not open source and applying licensing.
So let's go for izpack.

**Comment by fabmars** [comment]
Why David, why ? ¿Porque? Pourquoi?
Why do I have to struggle project after project on gradle? Of course the gradle plugin for izpack (http://github.com/bmuschko/gradle-izpack-plugin) isn't supported anymore and only works up to izpack 4.3.x - 2011 yay!

So, 3 options: upgrade the gradle plugin, switch to maven, or use another installer.
But I'm loco you know :)

**Comment by Draluy** [comment]
Or option 4: customize the build pipeline ourselves to produce a izpack binary or whatever.
Or 5: create a separate project to create the installer.

**Comment by fabmars** [comment]
bmuschko helped me, got it working with v5, just did PR.

Possible Evolutions:
- Embed a JRE to propose to install with the app (?)
- Not sure it's possible to select French by default in the language selection dialog

Issues: the .bat file opens a window, so the app needs to be launched differently (eg as a service)

**Comment by Draluy** [comment]
Thats not an issue, more like an oversight from my part. I need to change java to javaw in the .bat and that should be it.

**Comment by Draluy** [comment]
Also, when do you sleep.

**Comment by Draluy** [comment]
redeyed@reds-pc:/media/lymphocyte/projets/chocoratage/build$ java -jar distributions/chocoratage-1.0-SNAPSHOT-installer.jar 
Command line arguments: 
Using laf org.pushingpixels.substance.api.skin.SubstanceMistSilverLookAndFeel
SEVERE: com.izforge.izpack.api.exception.IzPackException: java.lang.reflect.InvocationTargetException

**Comment by Draluy** [comment]
This may be because I'm using a JDK 10

**Comment by Draluy** [comment]
`SEVERE: com.izforge.izpack.api.exception.IzPackException: java.lang.reflect.InvocationTargetException
com.izforge.izpack.api.exception.ContainerException: com.izforge.izpack.api.exception.IzPackException: java.lang.reflect.InvocationTargetException
        at com.izforge.izpack.core.container.AbstractContainer.initialise(AbstractContainer.java:312)
        at com.izforge.izpack.core.container.AbstractContainer.initialise(AbstractContainer.java:284)
        at com.izforge.izpack.installer.container.impl.GUIInstallerContainer.<init>(GUIInstallerContainer.java:38)
        at com.izforge.izpack.installer.bootstrap.InstallerGui.run(InstallerGui.java:54)
        at com.izforge.izpack.installer.bootstrap.Installer.launchInstall(Installer.java:294)
        at com.izforge.izpack.installer.bootstrap.Installer.start(Installer.java:238)
        at com.izforge.izpack.installer.bootstrap.Installer.main(Installer.java:78)
Caused by: com.izforge.izpack.api.exception.IzPackException: java.lang.reflect.InvocationTargetException
        at com.izforge.izpack.installer.container.impl.GUIInstallerContainer.resolveComponents(GUIInstallerContainer.java:105)
        at com.izforge.izpack.installer.container.impl.InstallerContainer.fillContainer(InstallerContainer.java:80)
        at com.izforge.izpack.core.container.AbstractContainer.initialise(AbstractContainer.java:304)
        ... 6 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1367)
        at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1342)
        at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
        at com.izforge.izpack.installer.container.impl.GUIInstallerContainer.resolveComponents(GUIInstallerContainer.java:92)
        ... 8 more
Caused by: java.lang.NullPointerException
        at org.pushingpixels.substance.internal.ui.SubstanceButtonUI.__org__pushingpixels__substance__internal__ui__SubstanceButtonUI__installDefaults(SubstanceButtonUI.java:169)
        at org.pushingpixels.substance.internal.ui.SubstanceButtonUI.installDefaults(SubstanceButtonUI.java)
        at java.desktop/javax.swing.plaf.basic.BasicButtonUI.installUI(BasicButtonUI.java:105)
        at org.pushingpixels.substance.internal.ui.SubstanceButtonUI.__org__pushingpixels__substance__internal__ui__SubstanceButtonUI__installUI(SubstanceButtonUI.java)
        at org.pushingpixels.substance.internal.ui.SubstanceButtonUI.installUI(SubstanceButtonUI.java)
        at java.desktop/javax.swing.JComponent.setUI(JComponent.java:685)
        at java.desktop/javax.swing.AbstractButton.setUI(AbstractButton.java:1753)
        at java.desktop/javax.swing.JButton.updateUI(JButton.java:141)
        at java.desktop/javax.swing.AbstractButton.init(AbstractButton.java:2136)
        at java.desktop/javax.swing.JButton.<init>(JButton.java:131)
        at com.izforge.izpack.gui.ButtonFactory.createButton(ButtonFactory.java:155)
        at com.izforge.izpack.installer.gui.DefaultNavigator.<init>(DefaultNavigator.java:96)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
        at org.picocontainer.injectors.AbstractInjector.newInstance(AbstractInjector.java:145)
        at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:342)
        at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
        at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
        at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
        at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
        at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
        at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
        at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:632)
        at org.picocontainer.parameters.BasicComponentParameter$1.resolveInstance(BasicComponentParameter.java:118)
        at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:136)
        at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
        at org.picocontainer.injectors.ConstructorInjector$CtorAndAdapters.getParameterArguments(ConstructorInjector.java:309)
        at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:335)
        at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
        at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
        at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
        at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
        at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
        at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
        at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:678)`

**Comment by Draluy** [comment]
see https://github.com/Insubstantial/insubstantial/issues/17

**Comment by Draluy** [comment]
see https://izpack.atlassian.net/browse/IZPACK-1594?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&showAll=true

Test with jdk8

**Comment by Draluy** [comment]
FIX: installer must be run with jdk 8
