### ISSUE TITLE
Config.readForbiddenPhrases is broken on OSX

### ISSUE THREAD

**Issue by fabmars** [Draluy/chocoratage#11]
Since 2dc9ea7482b61030a3c411ce50805199b465f241 on OSX 10.14 Mojave with JDK 13.0.1+9 2019-10-15

Exception in thread "main" java.nio.file.FileSystemNotFoundException
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:172)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:158)
	at java.base/java.nio.file.Path.of(Path.java:208)
	at java.base/java.nio.file.Paths.get(Paths.java:98)
	at fr.raluy.chocoratage.Config.readForbiddenPhrases(Config.java:103)
	at fr.raluy.chocoratage.Config.parse(Config.java:95)
	at fr.raluy.chocoratage.Main.main(Main.java:17)

There's a few similar reports on StackOverflow.

The previous method worked though.

**Comment by Draluy** [comment]
Reverted back the old code. Can you confirm that it works?

**Comment by fabmars** [comment]
Works now!

**Comment by Draluy** [comment]
Lol. Wasn't the point of java to be portable?
